// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIImbcPGMqyJx3pGjCyLVXMPFOroVB2rE',
    appId: '1:459396900685:web:40205caf830812f3cd7904',
    messagingSenderId: '459396900685',
    projectId: 'uts-mobile-alatberat-731b4',
    authDomain: 'uts-mobile-alatberat-731b4.firebaseapp.com',
    storageBucket: 'uts-mobile-alatberat-731b4.firebasestorage.app',
    measurementId: 'G-9HJBVXL6W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC2YBt2y_EEquUreL-PX7fd1wuUQDWUVo',
    appId: '1:459396900685:android:8266dadce2b31294cd7904',
    messagingSenderId: '459396900685',
    projectId: 'uts-mobile-alatberat-731b4',
    storageBucket: 'uts-mobile-alatberat-731b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEShok5nILWvIgJTux5aLpUBcs01mYd0E',
    appId: '1:459396900685:ios:3b013f0e6b7487cecd7904',
    messagingSenderId: '459396900685',
    projectId: 'uts-mobile-alatberat-731b4',
    storageBucket: 'uts-mobile-alatberat-731b4.firebasestorage.app',
    iosClientId: '459396900685-uhijn1kdpk2c55b7ds671tf3m3thc8o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.utsMobileAlatberat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEShok5nILWvIgJTux5aLpUBcs01mYd0E',
    appId: '1:459396900685:ios:3b013f0e6b7487cecd7904',
    messagingSenderId: '459396900685',
    projectId: 'uts-mobile-alatberat-731b4',
    storageBucket: 'uts-mobile-alatberat-731b4.firebasestorage.app',
    iosClientId: '459396900685-uhijn1kdpk2c55b7ds671tf3m3thc8o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.utsMobileAlatberat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIImbcPGMqyJx3pGjCyLVXMPFOroVB2rE',
    appId: '1:459396900685:web:3496657b8b4cd284cd7904',
    messagingSenderId: '459396900685',
    projectId: 'uts-mobile-alatberat-731b4',
    authDomain: 'uts-mobile-alatberat-731b4.firebaseapp.com',
    storageBucket: 'uts-mobile-alatberat-731b4.firebasestorage.app',
    measurementId: 'G-FLB56QGFGW',
  );
}
